import argparse
from _typeshed import Incomplete
from typing import Any, Dict

from scrapy.exceptions import UsageError as UsageError
from scrapy.utils.conf import arglist_to_dict as arglist_to_dict, feed_process_params_from_cli as feed_process_params_from_cli

class ScrapyCommand:
    requires_project: bool
    crawler_process: Incomplete
    default_settings: Dict[str, Any]
    exitcode: int
    settings: Incomplete
    def __init__(self) -> None: ...
    def set_crawler(self, crawler) -> None: ...
    def syntax(self): ...
    def short_desc(self): ...
    def long_desc(self): ...
    def help(self): ...
    def add_options(self, parser) -> None: ...
    def process_options(self, args, opts) -> None: ...
    def run(self, args, opts) -> None: ...

class BaseRunSpiderCommand(ScrapyCommand):
    def add_options(self, parser) -> None: ...
    def process_options(self, args, opts) -> None: ...

class ScrapyHelpFormatter(argparse.HelpFormatter):
    def __init__(
        self, prog, indent_increment: int = ..., max_help_position: int = ..., width: Incomplete | None = ...
    ) -> None: ...
    def format_part_strings(self, part_strings): ...
