from _typeshed import Incomplete

from scrapy.commands import ScrapyCommand as ScrapyCommand
from scrapy.exceptions import UsageError as UsageError
from scrapy.utils.template import render_templatefile as render_templatefile, string_camelcase as string_camelcase

def sanitize_module_name(module_name): ...
def extract_domain(url): ...

class Command(ScrapyCommand):
    requires_project: bool
    default_settings: Incomplete
    def syntax(self): ...
    def short_desc(self): ...
    def add_options(self, parser) -> None: ...
    exitcode: Incomplete
    def run(self, args, opts) -> None: ...
    @property
    def templates_dir(self): ...
