from _typeshed import Incomplete

from scrapy.commands import ScrapyCommand as ScrapyCommand
from scrapy.utils.versions import scrapy_components_versions as scrapy_components_versions

class Command(ScrapyCommand):
    default_settings: Incomplete
    def syntax(self): ...
    def short_desc(self): ...
    def add_options(self, parser) -> None: ...
    def run(self, args, opts) -> None: ...
