from _typeshed import Incomplete

class NotConfigured(Exception): ...
class _InvalidOutput(TypeError): ...
class IgnoreRequest(Exception): ...
class DontCloseSpider(Exception): ...

class CloseSpider(Exception):
    reason: Incomplete
    def __init__(self, reason: str = ...) -> None: ...

class StopDownload(Exception):
    fail: Incomplete
    def __init__(self, *, fail: bool = ...) -> None: ...

class DropItem(Exception): ...
class NotSupported(Exception): ...

class UsageError(Exception):
    print_help: Incomplete
    def __init__(self, *a, **kw) -> None: ...

class ScrapyDeprecationWarning(Warning): ...
class ContractFail(AssertionError): ...
