class NotConfigured(Exception): ...
class _InvalidOutput(TypeError): ...
class IgnoreRequest(Exception): ...
class DontCloseSpider(Exception): ...

class CloseSpider(Exception):
    reason: str
    def __init__(self, reason: str = ...) -> None: ...

class StopDownload(Exception):
    fail: bool
    def __init__(self, *, fail: bool = ...) -> None: ...

class DropItem(Exception): ...
class NotSupported(Exception): ...

class UsageError(Exception):
    print_help: bool
    def __init__(self, *a: object, **kw: object) -> None: ...

class ScrapyDeprecationWarning(Warning): ...
class ContractFail(AssertionError): ...
