from zope.interface import Interface

class ISpiderLoader(Interface):
    def from_settings(settings) -> None: ...
    def load(spider_name) -> None: ...
    def list() -> None: ...
    def find_by_request(request) -> None: ...
