from _typeshed import Incomplete

class SignalManager:
    sender: Incomplete
    def __init__(self, sender=...) -> None: ...
    def connect(self, receiver, signal, **kwargs): ...
    def disconnect(self, receiver, signal, **kwargs): ...
    def send_catch_log(self, signal, **kwargs): ...
    def send_catch_log_deferred(self, signal, **kwargs): ...
    def disconnect_all(self, signal, **kwargs): ...
