from _typeshed import Incomplete

from scrapy.interfaces import ISpiderLoader as ISpiderLoader
from scrapy.utils.misc import walk_modules as walk_modules
from scrapy.utils.spider import iter_spider_classes as iter_spider_classes

class SpiderLoader:
    spider_modules: Incomplete
    warn_only: Incomplete
    def __init__(self, settings) -> None: ...
    @classmethod
    def from_settings(cls, settings): ...
    def load(self, spider_name): ...
    def find_by_request(self, request): ...
    def list(self): ...
