from scrapy.utils.python import without_none_values as without_none_values

class DefaultHeadersMiddleware:
    def __init__(self, headers) -> None: ...
    @classmethod
    def from_crawler(cls, crawler): ...
    def process_request(self, request, spider) -> None: ...
