from scrapy import signals as signals

class DownloadTimeoutMiddleware:
    def __init__(self, timeout: int = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler): ...
    def spider_opened(self, spider) -> None: ...
    def process_request(self, request, spider) -> None: ...
