from _typeshed import Incomplete

from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.python import global_object_name as global_object_name, to_bytes as to_bytes
from scrapy.utils.request import request_httprepr as request_httprepr

def get_header_size(headers): ...
def get_status_size(response_status): ...

class DownloaderStats:
    stats: Incomplete
    def __init__(self, stats) -> None: ...
    @classmethod
    def from_crawler(cls, crawler): ...
    def process_request(self, request, spider) -> None: ...
    def process_response(self, request, response, spider): ...
    def process_exception(self, request, exception, spider) -> None: ...
