from _typeshed import Incomplete

from scrapy import signals as signals

class UserAgentMiddleware:
    user_agent: Incomplete
    def __init__(self, user_agent: str = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler): ...
    def spider_opened(self, spider) -> None: ...
    def process_request(self, request, spider) -> None: ...
