from _typeshed import Incomplete

from scrapy.exceptions import ScrapyDeprecationWarning as ScrapyDeprecationWarning, UsageError as UsageError
from scrapy.settings import BaseSettings as BaseSettings
from scrapy.utils.deprecate import update_classpath as update_classpath
from scrapy.utils.python import without_none_values as without_none_values

def build_component_list(compdict, custom: Incomplete | None = ..., convert=...): ...
def arglist_to_dict(arglist): ...
def closest_scrapy_cfg(path: str = ..., prevpath: Incomplete | None = ...): ...
def init_env(project: str = ..., set_syspath: bool = ...) -> None: ...
def get_config(use_closest: bool = ...): ...
def get_sources(use_closest: bool = ...): ...
def feed_complete_default_values_from_settings(feed, settings): ...
def feed_process_params_from_cli(
    settings, output, output_format: Incomplete | None = ..., overwrite_output: Incomplete | None = ...
): ...
