from _typeshed import Incomplete

DEFAULT_PYTHON_SHELLS: Incomplete

def get_shell_embed_func(shells: Incomplete | None = ..., known_shells: Incomplete | None = ...): ...
def start_python_console(namespace: Incomplete | None = ..., banner: str = ..., shells: Incomplete | None = ...) -> None: ...
