from _typeshed import Incomplete

from scrapy.exceptions import ScrapyDeprecationWarning as ScrapyDeprecationWarning

def deprecated(use_instead: Incomplete | None = ...): ...
def defers(func): ...
def inthread(func): ...
