from _typeshed import Incomplete
from time import time as time

def get_engine_status(engine): ...
def format_engine_status(engine: Incomplete | None = ...): ...
def print_engine_status(engine) -> None: ...
