def ftp_makedirs_cwd(ftp, path, first_call: bool = ...) -> None: ...
def ftp_store_file(*, path, file, host, port, username, password, use_active_mode: bool = ..., overwrite: bool = ...) -> None: ...
