from _typeshed import Incomplete
from collections.abc import Generator

from scrapy.item import Item as Item
from scrapy.utils.datatypes import LocalWeakReferencedCache as LocalWeakReferencedCache
from scrapy.utils.deprecate import ScrapyDeprecationWarning as ScrapyDeprecationWarning
from scrapy.utils.python import flatten as flatten, to_unicode as to_unicode

def arg_to_iter(arg): ...
def load_object(path): ...
def walk_modules(path): ...
def extract_regex(regex, text, encoding: str = ...): ...
def md5sum(file): ...
def rel_has_nofollow(rel): ...
def create_instance(objcls, settings, crawler, *args, **kwargs): ...
def set_environ(**kwargs) -> Generator[None, None, None]: ...
def walk_callable(node) -> Generator[Incomplete, None, None]: ...
def is_generator_with_return_value(callable): ...
def warn_on_generator_with_return_value(spider, callable) -> None: ...
