from _typeshed import Incomplete

from scrapy.utils.misc import load_object as load_object

def listen_tcp(portrange, host, factory): ...

class CallLaterOnce:
    def __init__(self, func, *a, **kw) -> None: ...
    def schedule(self, delay: int = ...) -> None: ...
    def cancel(self) -> None: ...
    def __call__(self): ...

def install_reactor(reactor_path, event_loop_path: Incomplete | None = ...) -> None: ...
def verify_installed_reactor(reactor_path) -> None: ...
def is_asyncio_reactor_installed(): ...
