from typing import Iterable, Optional, Union

from scrapy import Request as Request, Spider as Spider
from scrapy.utils.httpobj import urlparse_cached as urlparse_cached
from scrapy.utils.misc import load_object as load_object
from scrapy.utils.python import to_bytes as to_bytes, to_unicode as to_unicode

def request_fingerprint(
    request: Request, include_headers: Optional[Iterable[Union[bytes, str]]] = ..., keep_fragments: bool = ...
) -> str: ...
def request_authenticate(request: Request, username: str, password: str) -> None: ...
def request_httprepr(request: Request) -> bytes: ...
def referer_str(request: Request) -> Optional[str]: ...
def request_from_dict(d: dict, *, spider: Optional[Spider] = ...) -> Request: ...
