from _typeshed import Incomplete

from scrapy.utils.python import to_unicode as to_unicode

SSL_OP_NO_TLSv1_3: Incomplete

def ffi_buf_to_string(buf): ...
def x509name_to_string(x509name): ...
def get_temp_key_info(ssl_object): ...
def get_openssl_version(): ...
