from _typeshed import Incomplete

from scrapy.utils.python import to_unicode as to_unicode
from w3lib.url import *

def url_is_from_any_domain(url, domains): ...
def url_is_from_spider(url, spider): ...
def url_has_any_extension(url, extensions): ...
def parse_url(url, encoding: Incomplete | None = ...): ...
def escape_ajax(url): ...
def add_http_if_no_scheme(url): ...
def guess_scheme(url): ...
def strip_url(
    url, strip_credentials: bool = ..., strip_default_port: bool = ..., origin_only: bool = ..., strip_fragment: bool = ...
): ...
