from _typeshed import Incomplete

from scrapy import signals as signals

class CoreStats:
    stats: Incomplete
    start_time: Incomplete
    def __init__(self, stats) -> None: ...
    @classmethod
    def from_crawler(cls, crawler): ...
    def spider_opened(self, spider) -> None: ...
    def spider_closed(self, spider, reason) -> None: ...
    def item_scraped(self, item, spider) -> None: ...
    def response_received(self, spider) -> None: ...
    def item_dropped(self, item, spider, exception) -> None: ...
