from _typeshed import Incomplete

from scrapy import signals as signals
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.job import job_dir as job_dir

class SpiderState:
    jobdir: Incomplete
    def __init__(self, jobdir: Incomplete | None = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler): ...
    def spider_closed(self, spider) -> None: ...
    def spider_opened(self, spider) -> None: ...
    @property
    def statefn(self): ...
