from _typeshed import Incomplete
from collections.abc import Generator

from scrapy.exceptions import NotConfigured as NotConfigured, NotSupported as NotSupported
from scrapy.selector import Selector as Selector
from scrapy.spiders import Spider as Spider
from scrapy.utils.iterators import csviter as csviter, xmliter as xmliter
from scrapy.utils.spider import iterate_spider_output as iterate_spider_output

class XMLFeedSpider(Spider):
    iterator: str
    itertag: str
    namespaces: Incomplete
    def process_results(self, response, results): ...
    def adapt_response(self, response): ...
    def parse_node(self, response, selector): ...
    def parse_nodes(self, response, nodes) -> Generator[Incomplete, None, None]: ...

class CSVFeedSpider(Spider):
    delimiter: Incomplete
    quotechar: Incomplete
    headers: Incomplete
    def process_results(self, response, results): ...
    def adapt_response(self, response): ...
    def parse_row(self, response, row) -> None: ...
    def parse_rows(self, response) -> Generator[Incomplete, None, None]: ...
